export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGIN_COV_ERR = 'LOGIN_COV_ERR';
export const LOGIN_ADFS_ERR = 'LOGIN_ADFS_ERR';
export const SET_CLEAN_MSG = 'SET_CLEAN_MSG';
export const RENEW_TOKEN_ERROR = 'RENEW_TOKEN_ERROR';
export const RENEW_TOKEN_SUCCESS = 'RENEW_TOKEN_SUCCESS';
